plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/edwinete/Claude/ApexLab/website/website"
publishOrigin = "ui"
base = "/Users/edwinete/Claude/ApexLab/website"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]